# NLTK TOKENIZER AND TF-IDF VECTORIZER

In [1]:
import sys
sys.path.append('../')
from tokenizer import tokenizer
from vectorizer import vectorizer

import numpy as np
import pandas as pd
import sklearn as sk

import sklearn.feature_extraction
import sklearn.model_selection

/home/flo/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:628: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [2]:
data = pd.read_csv('../../_data/Reviews.csv') # Loading the dataset
X, y = data['Text'], data['Score']

In [3]:
# FOR TESTING : only select first 20000 samples
X, y = X[:20000], y[:20000]

In [4]:
tokenized_documents = tokenizer(X)

In [5]:
X, vect = vectorizer(tokenized_documents)

In [6]:
# most frequent words
# print("Top 10 most frequent words in the dataset")
# print(vect.get_feature_names_out()[:10])

# # least frequent words
# print("Top 10 least frequent words in the dataset")
# print(vect.get_feature_names_out()[-10:])

Top 10 most frequent words in the dataset


AttributeError: 'NoneType' object has no attribute 'get_feature_names_out'

In [16]:
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

print(X_train[0])

(16000, 300) (4000, 300) (16000,) (4000,)
[0.34593101 0.64705329 0.39303476 0.61258213 0.63854143 0.41181885
 0.72428919 0.72546319 0.72637821 0.5874699  0.58083521 0.67067198
 0.5842678  0.56803618 0.34056154 0.34208953 0.54222612 0.34919484
 0.63348614 0.41245863 0.52634968 0.55066479 0.35888535 0.54158758
 0.82999214 0.483154   0.43712909 0.18760427 0.44680249 0.40270519
 0.3022289  0.53741441 0.58051613 0.52602324 0.45939893 0.45133262
 0.45962772 0.3277334  0.44471224 0.622801   0.68501793 0.62947506
 0.44775486 0.54039307 0.63825804 0.58972613 0.6281952  0.44269936
 0.5799176  0.48824603 0.64968851 0.40351276 0.49453391 0.36597578
 0.65477114 0.222619   0.56195982 0.2405871  0.36054256 0.39472278
 0.53322958 0.4737347  0.33488118 0.40595684 0.41549118 0.65070493
 0.33404763 0.64397261 0.33827377 0.30826735 0.55167087 0.571222
 0.54039747 0.37948157 0.61124222 0.32121594 0.43261401 0.64813427
 0.56465281 0.52200733 0.69349334 0.37754534 0.43621541 0.7903021
 0.51228555 0.40177166 

# Naive Bayes Classifier
### Model starts here

In [14]:
from sklearn.naive_bayes import MultinomialNB

# Multinomial Naive Bayes
nb = MultinomialNB()
naive_bayes = nb.fit(X_train, y_train)
predicted = naive_bayes.predict(X_test)

# Metrics
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predicted))
print(metrics.classification_report(y_test, predicted))

[[   0    0    0    0  353]
 [   0    0    0    0  246]
 [   0    0    0    0  342]
 [   0    0    0    0  567]
 [   0    0    0    0 2492]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       353
           2       0.00      0.00      0.00       246
           3       0.00      0.00      0.00       342
           4       0.00      0.00      0.00       567
           5       0.62      1.00      0.77      2492

    accuracy                           0.62      4000
   macro avg       0.12      0.20      0.15      4000
weighted avg       0.39      0.62      0.48      4000



/home/flo/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/flo/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/flo/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [15]:
example = '''
awful
'''

# tokenize and vectorize it, then try to predict
# test = tokenizer([example])
# test_tfidf = vect.transform(test)
# print(naive_bayes.predict(test_tfidf))

AttributeError: 'NoneType' object has no attribute 'transform'