# NLTK TOKENIZER AND TF-IDF VECTORIZER

In [1]:
import sys
sys.path.append('../')
from tokenizer import tokenizer
from vectorizer import vectorizer

import numpy as np
import pandas as pd
import sklearn as sk

[nltk_data] Downloading package punkt to /home/assil/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
data = pd.read_csv('../../_data/Reviews.csv') # Loading the dataset
X, y = data['Text'], data['Score']

In [5]:
# FOR TESTING : only select first 20000 samples
X, y = X[:20000], y[:20000]

In [6]:
tokenized_documents = tokenizer(X)

In [7]:
X, vect = vectorizer(tokenized_documents)

/home/assil/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [8]:
# most frequent words
print("Top 10 most frequent words in the dataset")
print(vect.get_feature_names_out()[:10])

# least frequent words
print("Top 10 least frequent words in the dataset")
print(vect.get_feature_names_out()[-10:])

Top 10 most frequent words in the dataset
['0' '00' '000' '0003' '000kwh' '002' '008' '01' '0100' '0174']
Top 10 least frequent words in the dataset
['zuke' 'zukes' 'zupas' 'zuppa' 'zwieback' 'º' '¼' '½' 'çaykur' 'ît']


In [9]:
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

print(X_train[0])

(16000, 26658) (4000, 26658) (16000,) (4000,)
  (0, 20554)	0.3845362652831886
  (0, 6390)	0.3436631403149654
  (0, 14429)	0.3724722072082089
  (0, 4235)	0.20728370948487648
  (0, 17569)	0.2629960113653433
  (0, 23859)	0.15524178896215457
  (0, 11671)	0.2679384409265626
  (0, 8352)	0.23213222149909707
  (0, 21911)	0.29415770046654777
  (0, 16681)	0.19747406219111086
  (0, 1912)	0.14002887633461686
  (0, 26519)	0.14117053473926772
  (0, 26200)	0.13006169326147435
  (0, 23803)	0.12657510519567464
  (0, 841)	0.08667788302140157
  (0, 10901)	0.15433885114321025
  (0, 23821)	0.16630262302915325
  (0, 1653)	0.164344730408501
  (0, 23811)	0.15903521582936178
  (0, 11595)	0.13181371070406692
  (0, 12252)	0.08195440863309632


# Logistic Regression
### Model starts here

In [11]:
# import sklearn logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

logreg = LogisticRegression()
# Train the model using the training sets
logreg.fit(X_train, y_train)

# Predict the test set results
y_pred = logreg.predict(X_test)

# Print the accuracy
print("Accuracy: ", accuracy_score(y_test, y_pred))

# Print the classification report
print("Classification Report: \n", classification_report(y_test, y_pred))

# Print the confusion matrix
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))

Accuracy:  0.69525
Classification Report: 
               precision    recall  f1-score   support

           1       0.62      0.47      0.54       353
           2       0.50      0.07      0.12       246
           3       0.45      0.20      0.28       342
           4       0.44      0.21      0.28       567
           5       0.74      0.97      0.84      2492

    accuracy                           0.70      4000
   macro avg       0.55      0.38      0.41      4000
weighted avg       0.64      0.70      0.64      4000

Confusion Matrix: 
 [[ 166    5   13   14  155]
 [  53   16   39   24  114]
 [  20   10   70   59  183]
 [  10    1   26  118  412]
 [  18    0    7   56 2411]]


/home/assil/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
example = '''
ok
'''

# tokenize and vectorize it, then try to predict
test = tokenizer([example])
test_tfidf = vect.transform(test)
print(logreg.predict(test_tfidf))

[3]
